// frontends/react/src/pages/PhotoEditor/ui/PhotoEditorPage.tsx
import { useEffect, useRef } from "react";
import { mountPhotoEditor } from "@showcase-lab/photo-editor/mount";
import "@showcase-lab/photo-editor/style.css";

export function PhotoEditorPage() {
  const hostRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const { unmount } = mountPhotoEditor(el);
    return unmount;
  }, []);

  return (
    <section>
      <h1>Photo Editor</h1>
      <p className="lead">Кадрирование, поворот и цветокоррекция прямо в браузере.</p>
      <div ref={hostRef} />
    </section>
  );
}

// frontends/vue/src/pages/PhotoEditor/ui/PhotoEditorPage.vue
<script setup lang="ts">
import { PhotoEditorShell } from "@showcase-lab/photo-editor";
import "@showcase-lab/photo-editor/style.css";
</script>

<template>
  <section>
    <h1>Photo Editor</h1>
    <p class="lead">Кадрирование, поворот и цветокоррекция прямо в браузере.</p>
    <PhotoEditorShell />
  </section>
</template>
